language: node_js

dist: xenial

node_js:
    - "8"
    - "10"
    - "11"

cache: yarn

script:
    - set -e
    - yarn run lerna bootstrap
    - yarn run lint
    - yarn run build
    - set +e

jobs:
    include:
        - stage: Publish docs
          if: type = push AND fork = false AND tag IS blank
          script: lerna bootstrap && lerna run build && lerna exec '/bin/bash -c "test -f scripts/travis/publishDocs.sh && scripts/travis/publishDocs.sh"'
