language: node_js

dist: xenial

node_js:
    - "8"
    - "10"
    - "11"

cache: yarn

script:
    - yarn run lint
    - yarn run build

jobs:
    include:
        - stage: Publish docs
          if: type = push AND fork = false AND tag IS blank
          script: lerna exec '/bin/bash -c "test -f scripts/travis/publishDocs.sh && scripts/travis/publishDocs.sh"'
